# PostgreSQL Datasource (Primary)
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# PostgreSQL에 최적화된 방언 설정
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 
server.port=8081

#jwt
jwt.secret=change-me-in-production-change-me-in-production-1234
#jwt.expiration-ms=10000
jwt.expiration-ms=3600000

#Mybatis
mybatis.config-location=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath*:mybatis/mapper/**/*.xml

logging.level.org.mybatis=DEBUG
logging.level.com.example.back.mapper=TRACE

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# 멀티파트 업로드 활성화 (기본값 true)
spring.servlet.multipart.enabled=true

# 개별 파일 당 최대 크기 (예: 50MB)
spring.servlet.multipart.max-file-size=50MB

# 한 번의 HTTP 요청에 포함된 전체 데이터 크기 (예: 100MB)
spring.servlet.multipart.max-request-size=100MB

# 파일이 메모리에 기록되는 임계치 (이보다 크면 임시 디렉토리에 저장)
spring.servlet.multipart.file-size-threshold=2KB

file.upload-dir=C:/IETM_REPOSITORY
